// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_Hxvn_pI6dSe9XwevS90LsH7ZG3YYpI0',
    appId: '1:138190328647:web:e62e66bd49e562f76fb262',
    messagingSenderId: '138190328647',
    projectId: 'promocoes-30f45',
    authDomain: 'promocoes-30f45.firebaseapp.com',
    storageBucket: 'promocoes-30f45.appspot.com',
    measurementId: 'G-GGN2HNCBX8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRoyH8o5GFDbg0maVUhquhRM7pHyrai4Q',
    appId: '1:138190328647:android:4d0017b34a71d2fc6fb262',
    messagingSenderId: '138190328647',
    projectId: 'promocoes-30f45',
    storageBucket: 'promocoes-30f45.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYhCia4HFcQ9N9Nah8RuvSfpUQTbDz5o8',
    appId: '1:138190328647:ios:429d1b8cc1c6e92b6fb262',
    messagingSenderId: '138190328647',
    projectId: 'promocoes-30f45',
    storageBucket: 'promocoes-30f45.appspot.com',
    iosBundleId: 'com.example.promocoes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYhCia4HFcQ9N9Nah8RuvSfpUQTbDz5o8',
    appId: '1:138190328647:ios:440df12f82495c806fb262',
    messagingSenderId: '138190328647',
    projectId: 'promocoes-30f45',
    storageBucket: 'promocoes-30f45.appspot.com',
    iosBundleId: 'com.example.promocoes.RunnerTests',
  );
}
